CREATE DATABASE QR_VALIDATOR;

USE QR_VALIDATOR;

CREATE TABLE QR_DATA(

    INDEX_NUMBER VARCHAR(10) NOT NULL PRIMARY KEY,

    STUDENT_NAME VARCHAR(50) NOT NULL,

    FACULTY VARCHAR(50) NOT NULL
);